# Generated by Django 4.1.3 on 2024-03-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('information', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('contract_owner_address', models.CharField(max_length=255)),
                ('base_uri', models.CharField(max_length=255)),
                ('ticket_id', models.IntegerField()),
                ('ticket_name', models.CharField(max_length=255)),
                ('ticket_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_max_supply', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255)),
                ('contract_owner_address', models.CharField(max_length=255)),
                ('base_uri', models.CharField(max_length=255)),
                ('ticket_name', models.CharField(max_length=255)),
                ('ticket_symbol', models.CharField(max_length=255)),
                ('mint_club_site', models.CharField(max_length=255)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.event')),
            ],
        ),
    ]
